# Missing Completely at Random

In [286]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [287]:
df = pd.read_csv("data_science_job.csv")
print(df.shape)

(19158, 13)

In [288]:
df.drop(['enrollee_id', 'city','company_size'], axis=1,inplace=True)
df.head()

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_type,training_hours,target
0,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,36.0,1.0
1,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,Pvt Ltd,47.0,0.0
2,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,83.0,0.0
3,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,Pvt Ltd,52.0,1.0
4,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,Funded Startup,8.0,0.0

In [289]:
df2 = df.dropna(inplace=False)
# df.dropna(inplace=True)
print(df2.shape)

(8697, 10)

In [290]:
df2.isnull().sum()

city_development_index    0
gender                    0
relevent_experience       0
enrolled_university       0
education_level           0
major_discipline          0
experience                0
company_type              0
training_hours            0
target                    0
dtype: int64

In [291]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city_development_index  18679 non-null  float64
 1   gender                  14650 non-null  str
 2   relevent_experience     19158 non-null  str
 3   enrolled_university     18772 non-null  str
 4   education_level         18698 non-null  str
 5   major_discipline        16345 non-null  str
 6   experience              19093 non-null  float64
 7   company_type            13018 non-null  str
 8   training_hours          18392 non-null  float64
 9   target                  19158 non-null  float64
dtypes: float64(4), str(6)
memory usage: 1.5 MB

In [292]:
df.head()

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_type,training_hours,target
0,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,36.0,1.0
1,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,Pvt Ltd,47.0,0.0
2,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,83.0,0.0
3,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,Pvt Ltd,52.0,1.0
4,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,Funded Startup,8.0,0.0

In [293]:
df.isnull().sum()

city_development_index     479
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_type              6140
training_hours             766
target                       0
dtype: int64

In [294]:
# df['city_development_index'].fillna(df['city_development_index'].mean(), inplace=True)
# df['experience'].fillna(df['experience'].mean(), inplace=True)
# df['training_hours'].fillna(df['training_hours'].mean(), inplace=True)


# # df['gender'].mode()
# # returns a Series, not a single value.

# df['gender'].fillna(df['gender'].mode()[0], inplace=True)
# df['enrolled_university'].fillna(df['enrolled_university'].mode()[0], inplace=True)
# df['education_level'].fillna(df['education_level'].mode()[0], inplace=True)
# df['major_discipline'].fillna(df['major_discipline'].mode()[0], inplace=True)
# df['company_type'].fillna(df['company_type'].mode()[0], inplace=True)


# NEW STYLE

df.fillna({
    'city_development_index': df['city_development_index'].mean(),
    'experience': df['experience'].mean(),
    'training_hours': df['training_hours'].mean(),
    'gender': df['gender'].mode()[0],
    'enrolled_university': df['enrolled_university'].mode()[0],
    'education_level': df['education_level'].mode()[0],
    'major_discipline': df['major_discipline'].mode()[0],
    'company_type': df['company_type'].mode()[0]
}, inplace=True)

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_type,training_hours,target
0,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,Pvt Ltd,36.0,1.0
1,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,Pvt Ltd,47.0,0.0
2,0.624,Male,No relevent experience,Full time course,Graduate,STEM,5.0,Pvt Ltd,83.0,0.0
3,0.789,Male,No relevent experience,no_enrollment,Graduate,Business Degree,0.0,Pvt Ltd,52.0,1.0
4,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,Funded Startup,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...
19153,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,Pvt Ltd,42.0,1.0
19154,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,Pvt Ltd,52.0,1.0
19155,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,Pvt Ltd,44.0,0.0
19156,0.802,Male,Has relevent experience,no_enrollment,High School,STEM,0.0,Pvt Ltd,97.0,0.0
19157,0.855,Male,No relevent experience,no_enrollment,Primary School,STEM,2.0,Pvt Ltd,127.0,0.0

In [295]:
print(df['experience'].dtype)

float64

In [296]:
df.head()

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_type,training_hours,target
0,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,Pvt Ltd,36.0,1.0
1,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,Pvt Ltd,47.0,0.0
2,0.624,Male,No relevent experience,Full time course,Graduate,STEM,5.0,Pvt Ltd,83.0,0.0
3,0.789,Male,No relevent experience,no_enrollment,Graduate,Business Degree,0.0,Pvt Ltd,52.0,1.0
4,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,Funded Startup,8.0,0.0

## Converting cat to Num

1. Male Onehot 
2. relevent_exp Ordinal
3. enrolled_uni Ordinal
4. eduLevel Ordinal
5. major_discipline OneHot
6. company type One Hot

In [297]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

preprocessor = ColumnTransformer(
    transformers=[
        # One-Hot
        ('gender', OneHotEncoder(drop='first', handle_unknown='ignore'),
         ['gender']),

        ('major', OneHotEncoder(drop='first', handle_unknown='ignore'),
         ['major_discipline']),

        ('company_type', OneHotEncoder(drop='first', handle_unknown='ignore'),
         ['company_type']),

        # Ordinal
        ('relevent_exp',
         OrdinalEncoder(categories=[
             ['No relevent experience',
              'Has relevent experience']
         ]),
         ['relevent_experience']),

        ('enrolled_uni',
         OrdinalEncoder(categories=[
             ['no_enrollment',
              'Part time course',
              'Full time course']
         ]),
         ['enrolled_university']),

        ('education',
         OrdinalEncoder(categories=[
             ['Primary School',
              'High School',
              'Graduate',
              'Masters',
              'Phd']
         ]),
         ['education_level'])
    ],
    remainder='passthrough'
)

In [298]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target',axis=1),df['target'],test_size=0.2)
X2_train, X2_test, y2_train, y2_test= train_test_split(df2.drop('target',axis=1),df2['target'],test_size=0.2)

In [299]:
print(type(X_train))
print(type(X_test))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [300]:
X_train.head()

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_type,training_hours
14719,0.828951,Male,No relevent experience,Full time course,Graduate,STEM,3.0,Pvt Ltd,24.0
852,0.926000,Male,No relevent experience,no_enrollment,Masters,Other,15.0,Pvt Ltd,42.0
17036,0.828951,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,Pvt Ltd,17.0
10210,0.624000,Male,No relevent experience,Full time course,Graduate,STEM,4.0,Pvt Ltd,48.0
11856,0.939000,Female,Has relevent experience,no_enrollment,Masters,Other,10.0,Pvt Ltd,40.0

In [301]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)
X2_train = preprocessor.fit_transform(X2_train)
X2_test = preprocessor.transform(X2_test)

In [302]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

lr2 = LogisticRegression()
lr2.fit(X2_train,y2_train)
y2_pred = lr2.predict(X2_test)

c:\Users\Garv\Desktop\ml nbs\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Garv\Desktop\ml nbs\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [303]:
from sklearn.metrics import accuracy_score

In [304]:
print("With NAN modified with mean and mode",accuracy_score(y_test,y_pred))
print("With NaN drop",accuracy_score(y2_test,y2_pred))

With NAN modified with mean and mode 0.7544363256784968
With NaN drop 0.832183908045977